CREATE TABLE course_sections (
  id INT PRIMARY KEY AUTO_INCREMENT,
  course_id INT,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE course_contents (
  id INT PRIMARY KEY AUTO_INCREMENT,
  course_id INT,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  section_id INT,
  FOREIGN KEY (section_id) REFERENCES course_sections(id) ON DELETE CASCADE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);