CREATE TABLE questions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  course_id INT,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  user_id VARCHAR(36) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  reply TEXT,
  content_id INT,
  FOREIGN KEY (content_id) REFERENCES course_contents(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE upvotes(
  id INT PRIMARY KEY AUTO_INCREMENT,
  question_id INT,
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
  user_id VARCHAR(36) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);