ALTER TABLE users
MODIFY COLUMN id VARCHAR(36);

CREATE TABLE refresh_tokens (
  id INT PRIMARY KEY AUTO_INCREMENT,
  token VARCHAR(512) NOT NULL,
  user_id VARCHAR(36),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP 
);