ALTER TABLE users
ADD COLUMN first_name VARCHAR(100) NOT NULL,
ADD COLUMN last_name VARCHAR(100) NOT NULL,
ADD COLUMN username VARCHAR(100)

ALTER TABLE users
RENAME COLUMN hash password

ALTER TABLE users
DROP COLUMN salt

ALTER TABLE users
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP

ALTER TABLE users
MODIFY COLUMN username VARCHAR(100) UNIQUE

